### ISSUE TITLE
Can't find export option following instructions

### ISSUE THREAD

**Issue by JuanBarkhuizen** [daz3d/DazToUnity#3]
From the DTU Install instructions

Enable the Advanced Settings checkbox.
Select your Unity Version and Rendering Pipeline from the dropdown.
Click "Install Plugin". A window will popup for you to select a Unity Project to which to install the Unity plugin.

I have the plugin installed on (dzunitybridge.dll.v2022.1.3.7.zip), I've also tried the 2.0 version installed by DIM and cannot find any options to select unity versions or pipelines. Although it seems to work if I export it normally like the Daz to unity has always been, I'm wondering if I'm missing features or don't have the correct version.
![image_2022-07-10_041829997](https://user-images.githubusercontent.com/105664823/178128679-de96d7ec-79cf-49eb-9e96-21d63985f8c3.png)

**Comment by danielbui78** [comment]
Yes, that is an old version of the plugin in the screenshot.  The new version will list the exact version, revision and build number directly below the "Advanced Settings" check box.  Do you have multiple instances of Daz Studio installed on your computer?  Maybe one via DIM and another via Daz Central?  If so, make sure you have installed the plugin in the correct location for the instance that you are running.  Another thing to check is if you have multiple versions of the DazToUnity bridge installed.  Check the Help -> About Installed Plugins option from the main menu bar.  Look for DazToUnity.  Make sure there is only one instance of it.  Make sure the version number is 2022.1.3.7.

![Screenshot (39)](https://user-images.githubusercontent.com/11391924/178129515-a1896995-452d-4a7a-ae27-cb275751082c.png)

![Screenshot (38)](https://user-images.githubusercontent.com/11391924/178129518-6ca1dfbb-b565-40c8-8f06-88e15d490519.png)

**Comment by JuanBarkhuizen** [comment]
Awesome I got it working and it looks great, It was indeed as you mentioned I recently upgraded to windows 11 and my drive letters changed causing a new instance of Daz to be Installed. Really happy with how far this plugin. Thank you for helping me.
