### ISSUE TITLE
Issue with uDTU GetLightDirection.hlsl

### ISSUE THREAD

**Issue by JuanBarkhuizen** [daz3d/DazToUnity#4]
Using Daz to unity 2022.1.3.7 and the 2020+ URP Plugin, On a fresh unity project (URP selected when projects are created)
![image](https://user-images.githubusercontent.com/105664823/178398422-21c70dc8-4652-44a4-b737-6fcab211ac87.png)
Seems to work perfectly in Unity 2021.3 LTS URP 12.1.7
![image](https://user-images.githubusercontent.com/105664823/178398601-032fe7c9-f87c-40b4-ad33-7a53e2683876.png)
However, in unity 2020.3 LTS URP 10.9 I get at least 2 errors ( You can still enter play mode and they don't always show up)
![image](https://user-images.githubusercontent.com/105664823/178398731-4cd3c53c-f803-4d40-8aa5-a4e05104ca2b.png)
But when opening the LightDirectionURP the errors show up, Further when opening the other URP Shaders the most errors I've gotten regarding GetLightDirection.hlsl is 8. But I'm not sure how to trigger them all as I normally only get 2 or 3, all errors point to line 9
![image](https://user-images.githubusercontent.com/105664823/178399396-d4425381-3e20-40f5-9d74-8adb48d55cd3.png)

Not a major problem and I have not found any visual issues with it yet. but wanted to point it out

**Comment by danielbui78** [comment]
Thanks very much for pointing this out.  It's a bug that was fixed last year but apparently did not make it into the merged/refactored bridge.   I will try to incorporate it into the next release.

FYI, this is the fix: 
https://forum.unity.com/threads/shader-graph-of-urp-of-2020-2-does-not-support-custom-nodes-and-more-issue.1030321/

**Comment by JuanBarkhuizen** [comment]
Awesome, Thanks.
